In [0]:
!pip3 install tensorflow_text>=2.0.0rc0

In [0]:
import tensorflow_hub as hub
import numpy as np
import tensorflow_text

# Some texts of different lengths.
english_sentences = ["dog", "Puppies are nice.", "I enjoy taking long walks along the beach with my dog."]
italian_sentences = ["cane", "I cuccioli sono carini.", "Mi piace fare lunghe passeggiate lungo la spiaggia con il mio cane."]
japanese_sentences = ["犬", "子犬はいいです", "私は犬と一緒にビーチを散歩するのが好きです"]

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")

# Compute embeddings.
en_result = embed(english_sentences)
it_result = embed(italian_sentences)
ja_result = embed(japanese_sentences)

# Compute similarity matrix. Higher score indicates greater similarity.
similarity_matrix_it = np.inner(en_result, it_result)
similarity_matrix_ja = np.inner(en_result, ja_result)
# np.inner is just Sum of products for the two vectors

In [0]:
print(similarity_matrix_it

array([[0.96964586, 0.27347845, 0.25536817],
       [0.3772605 , 0.8931676 , 0.28806686],
       [0.24611363, 0.23792985, 0.93521523]], dtype=float32)

In [0]:
en_result

<tf.Tensor: shape=(3, 512), dtype=float32, numpy=
array([[-0.00525211, -0.03831199, -0.00922014, ...,  0.0217905 ,
         0.0628018 , -0.01622536],
       [-0.02267582, -0.06907186,  0.01550867, ...,  0.08762302,
        -0.00076925, -0.05410822],
       [ 0.01908831,  0.00955219, -0.04741291, ...,  0.03206479,
         0.03661666,  0.00331058]], dtype=float32)>

In [0]:
it_result

<tf.Tensor: shape=(3, 512), dtype=float32, numpy=
array([[ 0.01247474, -0.04704872, -0.0116076 , ...,  0.00828648,
         0.05655242, -0.01926563],
       [-0.00054214, -0.05353344, -0.00509426, ...,  0.0758197 ,
        -0.0206784 , -0.01833749],
       [ 0.02309686,  0.03299273, -0.0450268 , ...,  0.0260329 ,
         0.03097188, -0.00283149]], dtype=float32)>

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
